import { createVerify } from "node:crypto";
import { SESv2Client, SendEmailCommand, CreateEmailIdentityCommand, GetEmailIdentityCommand, GetAccountCommand } from "@aws-sdk/client-sesv2";
import { S3Client, GetObjectCommand } from "@aws-sdk/client-s3";
import { fromTemporaryCredentials } from "@aws-sdk/credential-providers";
import { simpleParser } from "mailparser";
import { CanonicalProviderError, type CanonicalEventType, type ProviderModule, type ProviderSendContext } from "../contracts";
import { accepted, decodeJson, event } from "../shared";

function credentials(context:ProviderSendContext){
  if(context.config.type!=="ses"||context.secret.type!=="ses")throw new Error("Invalid SES configuration");
  if(context.config.roleArn)return fromTemporaryCredentials({params:{RoleArn:context.config.roleArn,ExternalId:context.config.externalId,RoleSessionName:`envoy-${context.accountId}`},masterCredentials:context.secret.accessKeyId&&context.secret.secretAccessKey?{accessKeyId:context.secret.accessKeyId,secretAccessKey:context.secret.secretAccessKey,sessionToken:context.secret.sessionToken}:undefined});
  return context.secret.accessKeyId&&context.secret.secretAccessKey?{accessKeyId:context.secret.accessKeyId,secretAccessKey:context.secret.secretAccessKey,sessionToken:context.secret.sessionToken}:undefined;
}
function ses(context:ProviderSendContext){if(context.config.type!=="ses")throw new Error("Invalid SES configuration");return new SESv2Client({region:context.config.region,credentials:credentials(context)})}
function snsString(payload:Record<string,unknown>){const keys=payload.Type==="Notification"?["Message","MessageId","Subject","Timestamp","TopicArn","Type"]:["Message","MessageId","SubscribeURL","Timestamp","Token","TopicArn","Type"];return keys.filter(k=>payload[k]!==undefined).map(k=>`${k}\n${String(payload[k])}\n`).join("")}
async function verifySns(payload:Record<string,unknown>,expectedTopicArn:string){const url=String(payload.SigningCertURL??"");const parsed=new URL(url);if(parsed.protocol!=="https:"||!/(^|\.)amazonaws\.com$/.test(parsed.hostname)||String(payload.TopicArn)!==expectedTopicArn)return false;const certificate=await fetch(url).then(r=>{if(!r.ok)throw new Error("SNS certificate fetch failed");return r.text()});const verifier=createVerify(payload.SignatureVersion==="2"?"RSA-SHA256":"RSA-SHA1");verifier.update(snsString(payload));verifier.end();return verifier.verify(certificate,String(payload.Signature),"base64")}

const eventMap:Record<string,CanonicalEventType>={Send:"accepted",Delivery:"delivered",DeliveryDelay:"deferred",Bounce:"bounced",Reject:"failed",Open:"opened",Click:"clicked",Complaint:"complained",RenderingFailure:"failed",Subscription:"unsubscribed",Received:"inbound.received"};

export const sesModule:ProviderModule={
  descriptor:{type:"ses",displayName:"Amazon SES",capabilities:{nativeIdempotency:false,inboundMode:"object-reference",domainManagement:true,webhookSecurity:"SNS certificate signature and TopicArn",eventTypes:Object.keys(eventMap),attachments:true,scheduling:false}},
  sender:{async send(message,context){if(context.config.type!=="ses")throw new Error("Invalid SES configuration");try{const result=await ses(context).send(new SendEmailCommand({FromEmailAddress:`${message.from.name} <${message.from.email}>`,Destination:{ToAddresses:[message.to.email]},ReplyToAddresses:message.replyTo?[message.replyTo]:undefined,Content:{Simple:{Subject:{Data:message.subject,Charset:"UTF-8"},Body:{Html:{Data:message.html,Charset:"UTF-8"},Text:{Data:message.text,Charset:"UTF-8"}}}},ConfigurationSetName:context.config.configurationSet,EmailTags:Object.entries(message.tags).map(([Name,Value])=>({Name,Value}))}));return accepted(result.MessageId)}catch(error){const value=error as {$metadata?:{httpStatusCode?:number};name?:string;message?:string};const status=value.$metadata?.httpStatusCode;if(!status)throw new CanonicalProviderError(value.message??"SES request outcome is unknown","network",value.name??"ses_transport_error","unknown",true);const category=status===429?"rate_limit":status===401||status===403?"authentication":status>=500?"provider":"policy";throw new CanonicalProviderError(value.message??`SES returned HTTP ${status}`,category,value.name??`http_${status}`,"not_accepted",status===429||status>=500)}}},
  webhook:{async verify(request,_context,security){const expected=typeof security.expectedTopicArn==="string"?security.expectedTopicArn:"";let parsed:Record<string,unknown>;try{parsed=decodeJson(request.rawBody)}catch{return{valid:false,replaySafe:false,nativeType:"unknown",parsed:null}};let valid=false;try{valid=Boolean(expected)&&await verifySns(parsed,expected)}catch{}const timestamp=new Date(String(parsed.Timestamp??0)).getTime();let nativeType=String(parsed.Type??"unknown");if(parsed.Type==="Notification"){try{const nested=JSON.parse(String(parsed.Message)) as Record<string,unknown>;nativeType=String(nested.eventType??nested.notificationType??"unknown")}catch{}}return{valid,replaySafe:Number.isFinite(timestamp)&&Math.abs(Date.now()-timestamp)<5*60_000,providerEventId:typeof parsed.MessageId==="string"?parsed.MessageId:undefined,nativeType,parsed};},async normalize(verified){const envelope=verified.parsed as Record<string,unknown>;if(envelope.Type!=="Notification")return[];const p=JSON.parse(String(envelope.Message)) as Record<string,unknown>;const native=String(p.eventType??p.notificationType??"");const type=eventMap[native];if(!type)return[];const mail=(p.mail??{}) as Record<string,unknown>;const destination=Array.isArray(mail.destination)?mail.destination.map(String):[];const bounce=(p.bounce??{}) as Record<string,unknown>;return[event({id:verified.providerEventId??crypto.randomUUID(),externalMessageId:typeof mail.messageId==="string"?mail.messageId:undefined,type,occurredAt:new Date(String(mail.timestamp??new Date().toISOString())),recipient:destination[0],bounce:type==="bounced"?{classification:bounce.bounceType==="Permanent"?"hard":"soft",code:String(bounce.bounceSubType??"")}:undefined,inboundReference:type==="inbound.received"?String(mail.messageId??""):undefined})]}},
  identity:{async createIdentity(domain,context){const result=await ses(context).send(new CreateEmailIdentityCommand({EmailIdentity:domain}));return{externalIdentityId:domain,status:result.VerifiedForSendingStatus?"verified":"pending",dnsRecords:result.DkimAttributes?.Tokens?.map(token=>({type:"CNAME",name:`${token}._domainkey.${domain}`,value:`${token}.dkim.amazonses.com`}))??[]}},async checkIdentity(id,context){const result=await ses(context).send(new GetEmailIdentityCommand({EmailIdentity:id}));return{status:result.VerifiedForSendingStatus?"verified":"pending",dnsRecords:result.DkimAttributes?.Tokens?.map(token=>({type:"CNAME",name:`${token}._domainkey.${id}`,value:`${token}.dkim.amazonses.com`}))??[]}}},
  inbound:{async receive(verified,context){if(context.config.type!=="ses")throw new Error("Invalid SES configuration");const envelope=verified.parsed as Record<string,unknown>;const payload=JSON.parse(String(envelope.Message)) as Record<string,unknown>;const receipt=(payload.receipt??{}) as Record<string,unknown>;const action=Array.isArray(receipt.action)?receipt.action[0] as Record<string,unknown>:receipt.action as Record<string,unknown>|undefined;const mail=(payload.mail??{}) as Record<string,unknown>;if(!action||action.type!=="S3"||typeof action.bucketName!=="string"||typeof action.objectKey!=="string")return null;const object=await new S3Client({region:context.config.region,credentials:credentials(context)}).send(new GetObjectCommand({Bucket:action.bucketName,Key:action.objectKey}));if(!object.Body)throw new Error("SES inbound object is empty");const bytes=await object.Body.transformToByteArray();const parsed=await simpleParser(Buffer.from(bytes));return{externalMessageId:String(mail.messageId??action.objectKey),messageId:parsed.messageId,from:parsed.from?.text??"",to:parsed.to?Array.isArray(parsed.to)?parsed.to.map(x=>x.text):[parsed.to.text]:[],cc:parsed.cc?Array.isArray(parsed.cc)?parsed.cc.map(x=>x.text):[parsed.cc.text]:[],bcc:parsed.bcc?Array.isArray(parsed.bcc)?parsed.bcc.map(x=>x.text):[parsed.bcc.text]:[],subject:parsed.subject??"",html:typeof parsed.html==="string"?parsed.html:undefined,text:parsed.text,rawMime:bytes,attachments:parsed.attachments.map(a=>({fileName:a.filename??"attachment",contentType:a.contentType,content:new Uint8Array(a.content),contentId:a.cid})),receivedAt:parsed.date??new Date()}}},
  reconciliation:{async reconcile(){return"unknown"}},
  health:{async check(context){const result=await ses(context).send(new GetAccountCommand({}));return{healthy:result.ProductionAccessEnabled!==undefined,details:{productionAccess:result.ProductionAccessEnabled,sendingEnabled:result.SendingEnabled}}}},
};
