import type { PoolClient } from "pg";
import type { CanonicalEvent, ProviderType, WebhookVerification } from "@/modules/providers/contracts";
import { loadWebhookEndpoint } from "@/modules/config/webhook-endpoint";
import { objectStore } from "@/modules/config/object-store";
import { createId } from "@/server/ids";
import { query, transaction } from "@/server/database";
import { processInboundEvent } from "@/modules/inbound/service";

const lifecycleTypes=new Set(["accepted","deferred","delivered","bounced","failed"]);
function callbackType(type:string){return`email.${type}`}

async function addCallbacks(client:PoolClient,delivery:{id:string;message_id:string;service_id:string;reference_id:string|null;recipient_email:string;product:string;template_key:string;lifecycle_status:string;engagement_status:string;compliance_status:string},eventId:string,event:CanonicalEvent){const endpoints=await client.query<{id:string}>("SELECT id FROM callback_endpoints WHERE service_id=$1 AND status='active' AND $2=ANY(subscribed_events)",[delivery.service_id,callbackType(event.type)]);for(const endpoint of endpoints.rows){const id=createId("cbx");const payload={id:createId("event"),apiVersion:"2026-09-01",type:callbackType(event.type),occurredAt:event.occurredAt.toISOString(),data:{messageId:delivery.message_id,deliveryId:delivery.id,referenceId:delivery.reference_id,recipient:delivery.recipient_email,product:delivery.product,template:delivery.template_key,lifecycle:delivery.lifecycle_status,engagement:delivery.engagement_status,compliance:delivery.compliance_status}};await client.query("INSERT INTO callback_deliveries(id,endpoint_id,delivery_event_id,event_type,payload) VALUES ($1,$2,$3,$4,$5)",[id,endpoint.id,eventId,callbackType(event.type),payload]);await client.query("INSERT INTO outbox_events(id,aggregate_type,aggregate_id,event_type,payload) VALUES ($1,'callback',$2,'callback.requested',$3)",[createId("out"),id,{callbackDeliveryId:id}])}}

async function applySuppression(client:PoolClient,delivery:{recipient_email:string;product_id:string},event:CanonicalEvent){
  if(event.type==="complained"||event.type==="suppressed"||(event.type==="bounced"&&event.bounce?.classification==="hard")){await client.query(`INSERT INTO suppressions(id,scope_type,email_normalized,reason,source) VALUES ($1,'global',$2,$3,'provider_event') ON CONFLICT DO NOTHING`,[createId("sup"),delivery.recipient_email,event.type==="bounced"?"hard_bounce":event.type]);return}
  if(event.type==="unsubscribed"){const listId=typeof event.metadata.listId==="string"?event.metadata.listId:null;await client.query(`INSERT INTO suppressions(id,scope_type,product_id,list_id,email_normalized,reason,source) VALUES ($1,$2,$3,$4,$5,'unsubscribe','provider_event') ON CONFLICT DO NOTHING`,[createId("sup"),listId?"list":"product",delivery.product_id,listId,delivery.recipient_email]);return}
  if(event.type==="bounced"&&event.bounce?.classification==="soft"){const count=await client.query<{count:string}>(`SELECT count(*) FROM delivery_events de JOIN deliveries d ON d.id=de.delivery_id WHERE d.recipient_email=$1 AND de.event_type='bounced' AND de.occurred_at>now()-interval '30 days'`,[delivery.recipient_email]);if(Number(count.rows[0]?.count??0)>=3)await client.query(`INSERT INTO suppressions(id,scope_type,email_normalized,reason,source,bounce_count,expires_at) VALUES ($1,'global',$2,'soft_bounce_threshold','provider_event',$3,now()+interval '7 days') ON CONFLICT DO NOTHING`,[createId("sup"),delivery.recipient_email,Number(count.rows[0]?.count??0)])}
}

export async function applyCanonicalEvent(providerAccountId:string,rawEventId:string|null,event:CanonicalEvent){if(!event.externalMessageId)return false;return transaction(async client=>{const attempt=await client.query<{delivery_id:string}>("SELECT delivery_id FROM delivery_attempts WHERE provider_account_id=$1 AND external_message_id=$2",[providerAccountId,event.externalMessageId]);if(!attempt.rows[0])return false;const eventId=createId("dev");const inserted=await client.query("INSERT INTO delivery_events(id,delivery_id,raw_provider_event_id,event_type,occurred_at,canonical_payload) VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING RETURNING id",[eventId,attempt.rows[0].delivery_id,rawEventId,event.type,event.occurredAt,event]);if(!inserted.rowCount)return true;
    const later=await client.query("SELECT 1 FROM delivery_events WHERE delivery_id=$1 AND event_type=ANY($2::text[]) AND occurred_at>$3 LIMIT 1",[attempt.rows[0].delivery_id,lifecycleTypes.has(event.type)?[...lifecycleTypes]:event.type==="opened"||event.type==="clicked"?["opened","clicked"]:["complained","unsubscribed","suppressed"],event.occurredAt]);
    if(!later.rowCount){if(lifecycleTypes.has(event.type)){const lifecycle=event.type==="accepted"?"accepted":event.type;await client.query("UPDATE deliveries SET lifecycle_status=$2,accepted_at=CASE WHEN $2='accepted' THEN COALESCE(accepted_at,$3) ELSE accepted_at END,delivered_at=CASE WHEN $2='delivered' THEN $3 ELSE delivered_at END,updated_at=now() WHERE id=$1",[attempt.rows[0].delivery_id,lifecycle,event.occurredAt])}else if(event.type==="opened"||event.type==="clicked")await client.query("UPDATE deliveries SET engagement_status=$2,updated_at=now() WHERE id=$1",[attempt.rows[0].delivery_id,event.type]);else if(["complained","unsubscribed","suppressed"].includes(event.type))await client.query("UPDATE deliveries SET compliance_status=$2,updated_at=now() WHERE id=$1",[attempt.rows[0].delivery_id,event.type])}
    const delivery=(await client.query<{id:string;message_id:string;service_id:string;product_id:string;reference_id:string|null;recipient_email:string;product:string;template_key:string;lifecycle_status:string;engagement_status:string;compliance_status:string}>(`SELECT d.id,d.message_id,m.service_id,m.product_id,m.reference_id,d.recipient_email,p.name AS product,t.key AS template_key,d.lifecycle_status,d.engagement_status,d.compliance_status FROM deliveries d JOIN messages m ON m.id=d.message_id JOIN products p ON p.id=m.product_id JOIN templates t ON t.id=m.template_id WHERE d.id=$1`,[attempt.rows[0].delivery_id])).rows[0];if(delivery){await applySuppression(client,delivery,event);await addCallbacks(client,delivery,eventId,event)}return true})}

export async function applySuppressedDelivery(deliveryId:string){await transaction(async client=>{const eventId=createId("dev");const now=new Date();const inserted=await client.query("INSERT INTO delivery_events(id,delivery_id,event_type,occurred_at,canonical_payload) VALUES ($1,$2,'suppressed',$3,$4) ON CONFLICT DO NOTHING RETURNING id",[eventId,deliveryId,now,{id:eventId,type:"suppressed",occurredAt:now.toISOString(),metadata:{source:"suppression_policy"}}]);if(!inserted.rowCount)return;await client.query("UPDATE deliveries SET lifecycle_status='failed',compliance_status='suppressed',updated_at=now() WHERE id=$1",[deliveryId]);const delivery=(await client.query<{id:string;message_id:string;service_id:string;product_id:string;reference_id:string|null;recipient_email:string;product:string;template_key:string;lifecycle_status:string;engagement_status:string;compliance_status:string}>(`SELECT d.id,d.message_id,m.service_id,m.product_id,m.reference_id,d.recipient_email,p.name AS product,t.key AS template_key,d.lifecycle_status,d.engagement_status,d.compliance_status FROM deliveries d JOIN messages m ON m.id=d.message_id JOIN products p ON p.id=m.product_id JOIN templates t ON t.id=m.template_id WHERE d.id=$1`,[deliveryId])).rows[0];if(delivery)await addCallbacks(client,delivery,eventId,{id:eventId,type:"suppressed",occurredAt:now,recipient:delivery.recipient_email,metadata:{source:"suppression_policy"}})})}

export async function processRawProviderEvent(rawEventId:string){const raw=(await query<{id:string;provider_account_id:string;webhook_endpoint_id:string;opaque_token:string;provider_type:ProviderType;raw_body:Buffer|null;raw_object_key:string|null;headers:Record<string,string>;processed_at:Date|null}>(`SELECT r.id,r.provider_account_id,r.webhook_endpoint_id,e.opaque_token,a.type AS provider_type,r.raw_body,r.raw_object_key,r.headers,r.processed_at FROM raw_provider_events r JOIN provider_webhook_endpoints e ON e.id=r.webhook_endpoint_id JOIN provider_accounts a ON a.id=r.provider_account_id WHERE r.id=$1`,[rawEventId])).rows[0];if(!raw||raw.processed_at)return;try{const endpoint=await loadWebhookEndpoint(raw.provider_type,raw.opaque_token);if(!endpoint)throw new Error("Webhook endpoint is unavailable");const body=raw.raw_body?new Uint8Array(raw.raw_body):await objectStore().get(raw.raw_object_key??"");const headers={...raw.headers};if(headers.authorization==="[redacted]"){if(raw.provider_type==="mock"&&typeof endpoint.security.token==="string")headers.authorization=`Bearer ${endpoint.security.token}`;else if(raw.provider_type==="sendgrid"&&typeof endpoint.security.inboundToken==="string")headers.authorization=`Bearer ${endpoint.security.inboundToken}`;else if(raw.provider_type==="postmark"&&endpoint.context.secret.type==="postmark"){const username=typeof endpoint.security.username==="string"?endpoint.security.username:endpoint.context.secret.webhookUsername;const password=typeof endpoint.security.password==="string"?endpoint.security.password:endpoint.context.secret.webhookPassword;if(username&&password)headers.authorization=`Basic ${Buffer.from(`${username}:${password}`).toString("base64")}`}}const verified=await endpoint.module.webhook.verify({rawBody:body,headers,remoteAddress:headers["x-envoy-source-ip"]},endpoint.context,endpoint.security);if(!verified.valid)throw new Error("Persisted webhook no longer verifies");
    if(raw.provider_type==="ses"){const p=verified.parsed as Record<string,unknown>;if(p.Type==="SubscriptionConfirmation"&&typeof p.SubscribeURL==="string"){const u=new URL(p.SubscribeURL);if(u.protocol==="https:"&&/(^|\.)amazonaws\.com$/.test(u.hostname))await fetch(u)}}
    const events=await endpoint.module.webhook.normalize(verified as WebhookVerification,endpoint.context);for(const item of events){if(item.type==="inbound.received"&&endpoint.module.inbound)await processInboundEvent({providerAccountId:raw.provider_account_id,webhookEndpointId:raw.webhook_endpoint_id,rawEventId:raw.id,verified,receive:value=>endpoint.module.inbound!.receive(value,endpoint.context)});else await applyCanonicalEvent(raw.provider_account_id,raw.id,item)}await query("UPDATE raw_provider_events SET processed_at=now(),processing_error=NULL WHERE id=$1",[raw.id]);
  }catch(error){await query("UPDATE raw_provider_events SET processing_error=$2 WHERE id=$1",[raw.id,error instanceof Error?error.message:"Unknown event error"]);throw error}}
